[pytest]
markers =
    register: mark for register tests
    title: mark a test as a title test.
    valid_login: mark a test as a valid username and password test.
    invalid_username: mark a test as an invalid username test.
    invalid_password: mark a test as an invalid password test.
    add_to_cart: mark a test as an add to cart test and view cart test..


